#!/bin/bash

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
	echo "Usage: brightness_desktop BRIGHTNESS [--force]"
    exit 2
fi

BMIN=0.2
BMAX=3.0

if [ "$2" != "--force" ] && float-gt $BMIN "$1"; then
    echo "Brightness less than $BMIN, use --force"
    exit 1
fi

if [ "$2" != "--force" ] && float-gt "$1" $BMAX; then
    echo "Brightness greater than $BMAX, use --force"
    exit 1
fi

function first {
  _RETURN="$1"
}

if [ -z $OUTPUT ]; then
  OUTPUT="$(xrandr -q | grep " connected" | tail -n1)"
  first $OUTPUT
  OUTPUT="$_RETURN"
fi

if [ -z $OUTPUT ]; then
  echo "Couldn't find output"
  exit 1
fi

xrandr --output "$OUTPUT" --brightness $1
